src/app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('mockups/', include('mockups.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/mockups/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

app_name = 'mockups'

urlpatterns = [
    # path('login/', TemplateView.as_view(template_name='mockups/login.html'), name='login'),
    path('', TemplateView.as_view(template_name='mockups/home.html'), name='home'),
    path('dahsboard/', include([
        path('', TemplateView.as_view(template_name='mockups/dashboard/index.html'), name='dashboard'),
        path('stores/', TemplateView.as_view(template_name='mockups/dashboard/store_list.html'), name='store-list'),
        path('stores/44323248376/', TemplateView.as_view(template_name='mockups/dashboard/store_detail.html'), name='store-detail'),
        path('products/', TemplateView.as_view(template_name='mockups/dashboard/product_list.html'), name='product-list'),
        path('products/72948362/', TemplateView.as_view(template_name='mockups/dashboard/product_detail.html'), name='product-detail'),
        path('orders/', TemplateView.as_view(template_name='mockups/dashboard/order_list.html'), name='order-list'),
        path('orders/A64J9B32/', TemplateView.as_view(template_name='mockups/dashboard/order_detail.html'), name='order-detail'),
        path('orders/A64J9B32/item/737367463737373', TemplateView.as_view(template_name='mockups/dashboard/order_item_detail.html'), name='order-item-detail'),
    ])),
]

src/mockups/models.py
from django.db import models

# Create your models here.

src/mockups/views.py
from django.shortcuts import render

# Create your views here.

src/mockups/templates/mockups/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <title>EWI{% block title %}{% endblock %}</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui.structure.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui.theme.min.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">


        <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon/favicon.png">


        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div id="wrapper">

            {% block nav-container %}
                <div class="">
                    <nav>
                        {% block nav %}
                            {% include './navbar.html' %}
                        {% endblock %}
                    </nav>
                </div>
            {% endblock %}

            <div class="container-fluid">
            <div class="row">



               <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        {% block aside %}
                            {% include './aside.html' %}
                        {% endblock %}
                    </div>
                </nav>

                 <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

                        {% block content %}
                        {% endblock %}

                 </main>
            </div>


            </div>





            {% block footer-container %}
                <div class="">
                    <footer>
                        {% block footer %}
{#                            {% include './footer.html' %}#}
                        {% endblock %}
                    </footer>
                </div>
            {% endblock %}

        </div>

        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js">
</script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

        {% block js %}
        {% endblock %}
    </body>
</html>

src/mockups/templates/mockups/aside.html
<div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="#">
            <i class="fas fa-chart-line"></i>
          Dashboard
        </a>
        <hr>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mockups:store-list' %}">
            <i class="fas fa-store"></i>
          Shops
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mockups:product-list' %}">
            <i class="fas fa-tshirt"></i>
          Products
        </a>
      </li>
            <li class="nav-item">
        <a class="nav-link" href="{% url 'mockups:order-list' %}">
            <i class="fas fa-shopping-cart"></i>
          Orders
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">
            <i class="fas fa-exclamation-triangle"></i>
          Shops
        </a>
      </li>


    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Otros</span>
      <a class="d-flex align-items-center text-muted" href="#">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">

      <li class="nav-item">
        <a class="nav-link" href="#">
            <i class="fas fa-file"></i>
          Reporte 1
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
            <i class="fas fa-address-book"></i>
          Directorio
        </a>
      </li>
    </ul>
</div>

src/mockups/templates/mockups/dashboard/order_detail.html
{% extends '../_base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Order General Information</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled">
                            <li>Order ID: 12312312</li>
                            <li>Channel: OhLouLou (Shopify) Order: <a href="">#10032</a></li>
                            <li>Date: Aug, 13, 2018</li>
                            <li>Fulfilment Status: <span class="badge badge-danger">Unfulfiled</span></li>
                            <li>Order Status: <span class="badge badge-warning">Pending Delivery</span></li>
                            <li>Payment Status: <span class="badge badge-success">Paid</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Delivery Information</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled">
                            <li>Carrier: UPS</li>
                            <li>Tracking Number: UPS234234343243 <a href="">Live Tracking</a></li>
                            <li>Status: <span class="badge badge-success">Delivered</span></li>
                            <li>Address: 43434, This and this Lane, <br>Hollywood, 90210, CA, USA</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h3>Order Detail</h3>
            <table class="table">
                <thead>
                    <th></th>
                    <th>Product</th>
                    <th>Unit Price</th>
                    <th>Total</th>
                </thead>
                <tbody>
                    {% for item in '1234' %}
                        <tr>
                            <td><img src="https://source.unsplash.com/75x100?product" alt=""></td>
                            <td>
                                <h4>
                                    {{ item }} X Coffe Mug Camper 13oz
                                    <br>
                                    <a href="{% url 'mockups:order-item-detail' %}"><button class="btn btn-primary">Papi, fullfill</button></a>
                                </h4>
                                <hr>
                                <div class="text-right small">
                                    <h6 class="text-left">PAPI!, please fullfil me...</h6>

                                    <table class="table table-striped table-sm small text-center">
                                        <tr>
                                            <td><span class="font-weight-bold">PMGOA</span> <br><span class="badge badge-success ">Preferred</span></td>
                                            <td>{{ item }} for 4.00/piece</td>
                                            <td>Total: 400.00</td>
                                            <td>1 days <i class="fa fa-check text-success"></i></td>
                                            <td><button class="btn btn-sm btn-secondary">Choose</button></td>
                                        </tr>
                                        <tr>
                                            <td><span class="font-weight-bold">Other Asshole</span><br> <span class="badge badge-secondary small">Sponsored</span></td>
                                            <td>{{ item }} for 4.00/piece</td>
                                            <td>Total: 400.00</td>
                                            <td>10 days <i class="fa fa-times text-danger"></i></td>
                                            <td><button class="btn btn-sm btn-secondary">Choose</button></td>
                                        </tr><tr>
                                            <td><span class="font-weight-bold">The Other Guy...</span></td>
                                            <td>{{ item }} for 4.00/piece</td>
                                            <td>Total: 400.00</td>
                                            <td>10 days</td>
                                            <td><button class="btn btn-sm btn-secondary">Choose</button></td>
                                        </tr>
                                    </table>

                                </div>
                            </td>
                            <td>$4.66</td>
                            <td>$103.00</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3" class="text-right">Total</th>
                        <th>300.00</th>
                    </tr>

                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}

src/mockups/templates/mockups/dashboard/order_item_detail.html
{% extends '../_base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
              <h1>Fullfilment Battlefield...</h1>
            </div>

            <div class="col-12" style="display: flex">
                <img src="https://source.unsplash.com/120x180?product" alt="">
                <h2>Coffe Mug Camper 13oz</h2>
            </div>
        </div>
            <hr>
        <div class="row">
            <h3>Available Suppliers</h3>
            <table class="table">
                <thead>
                    <th>Supplier</th>
                    <th>Conditions</th>
                    <th>Pricing</th>
                    <th></th>
                </thead>
                <tbody>
                        <tr>
                            <td>
                                PMGOA
                                <a href=""><i class="fa fa-external-link-alt"></i></a>
                            </td>
                            <td>
                                We love you, please buy from us...
                            </td>
                            <td>$4.66 a piece / 500.00 total</td>
                            <td><button class="btn btn-success">Selected <i class="fa fa-check"></i></button></td>
                        </tr>

                         <tr>
                            <td>
                                This Other Guy
                                <a href=""><i class="fa fa-external-link-alt"></i></a>
                                <br>
                                <span class="badge badge-secondary">Sponsored</span>
                            </td>
                            <td>
                                10 day delivery
                            </td>
                            <td>$4.66 a piece / 500.00 total</td>
                            <td><button class="btn btn-primary">Select</button></td>
                        </tr>

                        <tr>
                            <td>
                                One more...
                                <a href=""><i class="fa fa-external-link-alt"></i></a>
                                <br>
                                <span class="badge badge-secondary">Sponsored</span>
                            </td>
                            <td>
                                10 day delivery
                                <br>
                                <span class="badge badge-success"> Other items with the supplier</span>
                            </td>
                            <td>$4.66 a piece / 500.00 total</td>
                            <td><button class="btn btn-primary">Select</button></td>
                        </tr>

                        <tr>
                            <td>
                                One more...
                                <a href=""><i class="fa fa-external-link-alt"></i></a>
                                <br>
                                <span class="badge badge-secondary">Sponsored</span>
                            </td>
                            <td>
                                10 day delivery
                                <br>
                                <span class="badge badge-success"> Other items with the supplier of the same category</span>
                            </td>
                            <td>$4.66 a piece / 500.00 total</td>
                            <td><button class="btn btn-primary">Select</button></td>
                        </tr>

                </tbody>

            </table>
        </div>
        <div class="text-center">
            <button class="btn btn-primary">Next Item...</button>
        </div>
    </div>
{% endblock %}

src/mockups/templates/mockups/dashboard/order_list.html
{% extends '../_base.html' %}

{% block content %}
    <table class="table table-sm table-hover table-striped">
        <thead>
            <th>Shop</th>
            <th>Carried</th>
            <th>Satus</th>
        </thead>
        <tbody>
            {% for item in '12345' %}
                <tr>
                    <td><a href="{% url 'mockups:order-detail' %}"> 36534534098</a></td>
                    <td>Shopify</td>
                </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}

src/mockups/templates/mockups/dashboard/product_detail.html
{% extends '../_base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Camper Coffe Mug 13oz</h4>
                    </div>
                    <div class="card-body">

                        <img src="https://source.unsplash.com/random/250x100" alt="">
                        <ul class="list-unstyled">
                            <li>Product: Coffe Mug</li>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ul>
                        <table class="table table-sm table-striped">
                            <thead>
                                <th>Channel</th>
                                <th>Price</th>
                                <th>Sold</th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>OhLuLou</td>
                                    <td>$6.00</td>
                                    <td>125 ($44,565.00)</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/mockups/templates/mockups/dashboard/product_list.html
{% extends '../_base.html' %}

{% block content %}
    <table class="table table-sm table-hover table-striped">
        <thead>
            <th>Product</th>
            <th>Channels</th>
            <th>Sales</th>
        </thead>
        <tbody>
            {% for item in '12345' %}
                <tr>
                    <td><a href="{% url 'mockups:product-detail' %}">45345288</a></td>
                    <td>Coffe Mug Camper 13oz.</td>
                    <td>$23,4545.00</td>
                </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}

src/mockups/templates/mockups/dashboard/store_list.html
{% extends '../_base.html' %}

{% block content %}
    <table class="table table-sm table-hover table-striped">
        <thead>
            <th>Shop</th>
            <th>Carried</th>
            <th>Satus</th>
        </thead>
        <tbody>
            {% for item in '12345' %}
                <tr>
                    <td>OhLoulu.com</td>
                    <td>Shopify</td>
                </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}

src/mockups/templates/mockups/home.html
{% extends './_base.html' %}

src/mockups/templates/mockups/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="/">
      <img src="{% static 'images/favicon/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      EWI
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% block default-nav-buttons %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'mockups:store-list' %}">Shops</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'mockups:product-list' %}">Products</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'mockups:order-list' %}">Orders</a>
      </li>
      {% endblock %}
      {% block extra-nav-buttons %}
      {% endblock %}
    </ul>

    {% block right-navbar %}
    <ul class="nav navbar-nav navbar-right">
        {% block right-nav-buttons %}
        {% endblock %}
    </ul>
    {% endblock %}


  </div>
</nav>